### ISSUE TITLE
Index page refactoring

### ISSUE THREAD

**Issue by AceroM** [huntercodefest/huntercodefest.github.io#13]
- [x] Combine what it is and about us sections.
- [x] Replace the penguin images with images from last years codefest.
- [x] Combine the Alumni's and current team to appear in the same section.

## Stretch Goals
- [ ] Update the slideshow.

**Comment by Farhene** [comment]
I got rid of theme on navbar, since it is a button already available by the title. Let me know if that is okay. 
I also added resource to be at the right side near blog too so it can be linked to hopefully a page of google doc links?
![image](https://user-images.githubusercontent.com/44058427/97389455-8bd43280-1897-11eb-960e-121b4f9f2f6d.png)
The above pic is an updated navbar to make it less crowded.
I also made a section near blog called resources there. Will work on that later after I replace the penguins.

**Comment by Farhene** [comment]
![image](https://user-images.githubusercontent.com/44058427/97389516-b7efb380-1897-11eb-9917-665c997d99fb.png)
![image](https://user-images.githubusercontent.com/44058427/97389532-bcb46780-1897-11eb-9907-e3a0f0101f1b.png)
I condensed the paragraphs and put "our goal" instead there.

**Comment by Farhene** [comment]
![image](https://user-images.githubusercontent.com/44058427/97757681-98dd6580-1ad3-11eb-9ee9-e6b9675ef75d.png)
Currently finishing Up resources Page!! Almost done by tonight finally on this page! This way we don't have to rely on a google docs for the resources list! It would be directly linked to the website.
I plan on editing the navbar perhaps but will see.

**Comment by Farhene** [comment]
SO far my changes I did:
First:
![image](https://user-images.githubusercontent.com/44058427/97766384-7b68c580-1aec-11eb-8e16-107a5cb3b4fa.png)
![image](https://user-images.githubusercontent.com/44058427/97766394-83286a00-1aec-11eb-9aa2-a867c367d0c8.png)
Uploaded these two pics instead of the penguins,

Second:
![image](https://user-images.githubusercontent.com/44058427/97766725-144c1080-1aee-11eb-80ca-8e3ea8dac177.png)
![image](https://user-images.githubusercontent.com/44058427/97766735-2a59d100-1aee-11eb-8212-91125aff1b03.png)

I added a resources navbar to navigate for the resources section. And I collected all the old resources info to this resources page!

However, I am having trouble with figuring out how to deal with the buttons being shifted left when they're in the same box.
![image](https://user-images.githubusercontent.com/44058427/97766746-347bcf80-1aee-11eb-973f-21aefbecb549.png)
